get https://localhost/api


###

get https://localhost/api/tasks

###

get https://localhost/api/tasks/f8e2c83c-70c1-420b-b346-f88e01ada527

###

post https://localhost/api/tasks
Content-Type: application/json

{
  "title": "Apprendre Rust",
  "description": "Apprendre Rust pour faire des applications performantes"
}

###

patch https://localhost/api/tasks/f8e2c83c-70c1-420b-b346-f88e01ada527
Content-Type: application/json

{
  "title": "Task 1",
  "description": "Description 1",
  "completed": false
}

###
patch https://localhost/api/tasks/f8e2c83c-70c1-420b-b346-f88e01ada527
Content-Type: application/json

{
  "title": "Apprendre Rust",
  "description": "J'adore Rust",
  "completed": false
}

###
delete https://localhost/api/tasks/f8e2c83c-70c1-420b-b346-f88e01ada527

###
patch https://localhost/api/tasks/f8e2c83c-70c1-420b-b346-f88e01ada527/restore

###
delete https://localhost/api/tasks/f8e2c83c-70c1-420b-b346-f88e01ada527/destroy
